export const GET_INFO = "GET_INFO";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const GET_PRODUCERS = "GET_PRODUCERS";
export const GET_COINMARKETCAP = "GET_COINMARKETCAP";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
